Eigenentwicklungen aus Antragstext eweitert
missgreenwood/foss-concept pull request #21
Opened 2020-10-28 20:01 UTC by klml

Eigenentwicklungen aus Antrag [Neue Software im Open Source-Kontext entwickeln!](https://www.muenchen-transparent.de/antraege/6289779) erweitert.

* Begründung und zeitlichen Stufenplan raus genommen
* liste
* links (intern extern)
* Clean Code begründet

2020-10-28 21:47 UTC, DirkGern commented
Aus meiner Sicht passt das alles.

2020-10-29 20:10 UTC, missgreenwood requested changes

2020-10-29 20:10 UTC, missgreenwood commented on README.md
Wunderbar, vielen Dank.

2020-10-29 20:10 UTC, missgreenwood commented on contribution-guidelines.md
> +
Siehe Kommentar zu PR #20.

2020-11-04 16:18 UTC, missgreenwood approved these changes

2020-11-04 16:19 UTC, merged